"""Open Banking Reach + AIS  PIS.

# REACH The Reach Directory is used to get the a list of ASPSP's which can be reached for a  specific Service. **Sandbox** The following authorization token can be used to test in the sandbox (unlike a real token this one doesn't expire) 97fb13a74c712d8c7a50476e71769eaf  # AIS There are several possible flows (sequence of API calls) to obtain a consent before Account Information data can be retrieved. Which API's are required depend on the ASPSP (the bank of the PSU) and the chosen strong customer authentication approach. The response of an API call will indicate in the Links section which next API call is required to complete the consent request.  **Sandbox** Several AspspId's are available to test specific account information scenario's, see sandbox     documentation. The following authorization token can be used to test in the sandbox (unlike a real token this one     doesn't expire) **d5bd895a4080dbbb469a207460b6fca**  # PIS There are several flows (sequence of API calls) to complete a payment. Which API's are required depend on the choosen `PaymentProduct`, ASPSP (debtor bank) and the chosen strong customer authentication approach. The response of an API call will indicate in the 'Links' section which next API call is required to complete the payment. Both PSD2 and IDEAL payments are supported. **Sandbox** Several AspspId's are available to test specific PSD2 payment initiation scenario's, see sandbox documentation.  The following authorization token can be used to test in the sandbox (unlike a real token this one doesn't expire): **97fb13a74c712d8c7a50476e71769eaf**

OpenAPI spec version: 3.2.0 + 3.6.0 + 3.7.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class PaymentInitiationServiceApi:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None) -> None:
        """Initialize PaymentInitiationServiceApi."""
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def payment_authorisation(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment authorisation request.

        Use this operation to authorise a PSU explicitly. This has to be used if multiple PSU's have to authorise the payment. Background information: If only one PSU has to authorise, this step is started implicitly by the post payments api.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_authorisation(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentAuthorisationRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_authorisation_with_http_info(
                x_request_id, message_create_date_time, payment_id, **kwargs
            )
        return self.payment_authorisation_with_http_info(
            x_request_id, message_create_date_time, payment_id, **kwargs
        )

    def payment_authorisation_with_http_info(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment authorisation request.

        Use this operation to authorise a PSU explicitly. This has to be used if multiple PSU's have to authorise the payment. Background information: If only one PSU has to authorise, this step is started implicitly by the post payments api.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_authorisation_with_http_info(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentAuthorisationRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["x_request_id", "message_create_date_time", "payment_id", "body"]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_authorisation"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_authorisation`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_authorisation`"
            )
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_authorisation`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/authorisations",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentAuthorisationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_authorisation_update(
        self,
        x_request_id,
        message_create_date_time,
        payment_id,
        authorisation_id,
        **kwargs,
    ):
        """Payment authorisation request.

        Use this operation to change the authorisation resource.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_authorisation_update(x_request_id, message_create_date_time, payment_id, authorisation_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str authorisation_id: The Id used by the Open Banking Service to refer to an authorisation resource.  (required)
        :param PaymentAuthorisationUpdateRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_authorisation_update_with_http_info(
                x_request_id,
                message_create_date_time,
                payment_id,
                authorisation_id,
                **kwargs,
            )
        return self.payment_authorisation_update_with_http_info(
            x_request_id,
            message_create_date_time,
            payment_id,
            authorisation_id,
            **kwargs,
        )

    def payment_authorisation_update_with_http_info(
        self,
        x_request_id,
        message_create_date_time,
        payment_id,
        authorisation_id,
        **kwargs,
    ):
        """Payment authorisation request.

        Use this operation to change the authorisation resource.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_authorisation_update_with_http_info(x_request_id, message_create_date_time, payment_id, authorisation_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str authorisation_id: The Id used by the Open Banking Service to refer to an authorisation resource.  (required)
        :param PaymentAuthorisationUpdateRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "x_request_id",
            "message_create_date_time",
            "payment_id",
            "authorisation_id",
            "body",
        ]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_authorisation_update"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_authorisation_update`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_authorisation_update`"
            )
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_authorisation_update`"
            )
        # verify the required parameter 'authorisation_id' is set
        if "authorisation_id" not in params or params["authorisation_id"] is None:
            raise ValueError(
                "Missing the required parameter `authorisation_id` when calling `payment_authorisation_update`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]
        if "authorisation_id" in params:
            path_params["authorisationId"] = params["authorisation_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/authorisations/{authorisationId}",
            "PUT",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentAuthorisationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_cancellation(
        self, payment_id, x_request_id, message_create_date_time, **kwargs
    ):
        """Payment cancellation request.

        Use this operation to cancel a payment on behalf of the Payment Service User. Strong Customer Authentication might be required by the ASPSP, the response will indicate which step is required to complete the cancellation.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation(payment_id, x_request_id, message_create_date_time, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str initiating_party_return_url: The callback URL for the redirection back to the Initiating Party after authorization.
        :param str aspsp_psu_id: PSU Id at ASPSP. Allows the unique identification of the PSU at the ASPSP.
        :param str aspsp_psu_id_type: Type of the Aspsp PSU-ID, needed in scenarios where PSUs have several PSU-IDs as access possibility.
        :param str aspsp_psu_corporate_id: Identification of a Corporate in the Online Channels.
        :param str aspsp_psu_corporate_id_type: This is describing the type of the identification needed by the ASPSP to identify the PSUCorporate-ID type.
        :param bool use_authorisation_landing_pages: If true, the Bank Selection Interface provided by Open Banking Service will be used to request required information from the PSU directly.
        :param str locale: 2-digit ISO-639 code for the language in which the Bank Selection Interface is displayed.  For special languages can be used 5-digit code like nl-BE, where first is ISO-639 langauge code and the second is ISO-3166 country code.  If not set, the language of the Bank Selection Interface is taken over from the end user’s browser configuration or the system configuration of the Bank Selection Interface server.
        :param str psu_ip_address: PSU Session information.  The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP . It shall be contained if and only if this request was actively initiated by the PSU.
        :return: PaymentCancellationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_cancellation_with_http_info(
                payment_id, x_request_id, message_create_date_time, **kwargs
            )
        return self.payment_cancellation_with_http_info(
            payment_id, x_request_id, message_create_date_time, **kwargs
        )

    def payment_cancellation_with_http_info(
        self, payment_id, x_request_id, message_create_date_time, **kwargs
    ):
        """Payment cancellation request.

        Use this operation to cancel a payment on behalf of the Payment Service User. Strong Customer Authentication might be required by the ASPSP, the response will indicate which step is required to complete the cancellation.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation_with_http_info(payment_id, x_request_id, message_create_date_time, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str initiating_party_return_url: The callback URL for the redirection back to the Initiating Party after authorization.
        :param str aspsp_psu_id: PSU’s Id at ASPSP. Allows the unique identification of the PSU at the ASPSP.
        :param str aspsp_psu_id_type: Type of the Aspsp PSU-ID, needed in scenarios where PSUs have several PSU-IDs as access possibility.
        :param str aspsp_psu_corporate_id: Identification of a Corporate in the Online Channels.
        :param str aspsp_psu_corporate_id_type: This is describing the type of the identification needed by the ASPSP to identify the PSUCorporate-ID type.
        :param bool use_authorisation_landing_pages: If true, the Bank Selection Interface provided by Open Banking Service will be used to request required information from the PSU directly.
        :param str locale: 2-digit ISO-639 code for the language in which the Bank Selection Interface is displayed.  For special languages can be used 5-digit code like nl-BE, where first is ISO-639 langauge code and the second is ISO-3166 country code.  If not set, the language of the Bank Selection Interface is taken over from the end user’s browser configuration or the system configuration of the Bank Selection Interface server.
        :param str psu_ip_address: PSU Session information.  The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP . It shall be contained if and only if this request was actively initiated by the PSU.
        :return: PaymentCancellationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "payment_id",
            "x_request_id",
            "message_create_date_time",
            "initiating_party_return_url",
            "aspsp_psu_id",
            "aspsp_psu_id_type",
            "aspsp_psu_corporate_id",
            "aspsp_psu_corporate_id_type",
            "use_authorisation_landing_pages",
            "locale",
            "psu_ip_address",
        ]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_cancellation"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_cancellation`"
            )
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_cancellation`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_cancellation`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]
        if "initiating_party_return_url" in params:
            header_params["InitiatingPartyReturnUrl"] = params[
                "initiating_party_return_url"
            ]
        if "aspsp_psu_id" in params:
            header_params["AspspPsuId"] = params["aspsp_psu_id"]
        if "aspsp_psu_id_type" in params:
            header_params["AspspPsuIdType"] = params["aspsp_psu_id_type"]
        if "aspsp_psu_corporate_id" in params:
            header_params["AspspPsuCorporateId"] = params["aspsp_psu_corporate_id"]
        if "aspsp_psu_corporate_id_type" in params:
            header_params["AspspPsuCorporateIdType"] = params[
                "aspsp_psu_corporate_id_type"
            ]
        if "use_authorisation_landing_pages" in params:
            header_params["UseAuthorisationLandingPages"] = params[
                "use_authorisation_landing_pages"
            ]
        if "locale" in params:
            header_params["Locale"] = params["locale"]
        if "psu_ip_address" in params:
            header_params["PsuIpAddress"] = params["psu_ip_address"]

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}",
            "DELETE",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentCancellationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_cancellation_authorisation(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment cancellation authorisation request.

        Use this operation to authorise a Payment Service User (PSU) explicitly.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation_authorisation(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentAuthorisationRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_cancellation_authorisation_with_http_info(
                x_request_id, message_create_date_time, payment_id, **kwargs
            )
        return self.payment_cancellation_authorisation_with_http_info(
            x_request_id, message_create_date_time, payment_id, **kwargs
        )

    def payment_cancellation_authorisation_with_http_info(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment cancellation authorisation request.

        Use this operation to authorise a Payment Service User (PSU) explicitly.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation_authorisation_with_http_info(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentAuthorisationRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["x_request_id", "message_create_date_time", "payment_id", "body"]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_cancellation_authorisation"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_cancellation_authorisation`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_cancellation_authorisation`"
            )
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_cancellation_authorisation`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/cancellation-authorisations",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentAuthorisationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_cancellation_authorisation_update(
        self,
        x_request_id,
        message_create_date_time,
        payment_id,
        authorisation_id,
        **kwargs,
    ):
        """Payment cancellation authorisation request update.

        Use this operation to update the authorisation resource.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation_authorisation_update(x_request_id, message_create_date_time, payment_id, authorisation_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str authorisation_id: The Id used by the Open Banking Service to refer to an authorisation resource.  (required)
        :param PaymentAuthorisationUpdateRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_cancellation_authorisation_update_with_http_info(
                x_request_id,
                message_create_date_time,
                payment_id,
                authorisation_id,
                **kwargs,
            )
        return self.payment_cancellation_authorisation_update_with_http_info(
            x_request_id,
            message_create_date_time,
            payment_id,
            authorisation_id,
            **kwargs,
        )

    def payment_cancellation_authorisation_update_with_http_info(
        self,
        x_request_id,
        message_create_date_time,
        payment_id,
        authorisation_id,
        **kwargs,
    ):
        """Payment cancellation authorisation request update.

        Use this operation to update the authorisation resource.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation_authorisation_update_with_http_info(x_request_id, message_create_date_time, payment_id, authorisation_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str authorisation_id: The Id used by the Open Banking Service to refer to an authorisation resource.  (required)
        :param PaymentAuthorisationUpdateRequest body:
        :return: PaymentAuthorisationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "x_request_id",
            "message_create_date_time",
            "payment_id",
            "authorisation_id",
            "body",
        ]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_cancellation_authorisation_update"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_cancellation_authorisation_update`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_cancellation_authorisation_update`"
            )
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_cancellation_authorisation_update`"
            )
        # verify the required parameter 'authorisation_id' is set
        if "authorisation_id" not in params or params["authorisation_id"] is None:
            raise ValueError(
                "Missing the required parameter `authorisation_id` when calling `payment_cancellation_authorisation_update`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]
        if "authorisation_id" in params:
            path_params["authorisationId"] = params["authorisation_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/cancellation-authorisations/{authorisationId}",
            "PUT",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentAuthorisationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_cancellation_identification(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment cancellation identification request.

        Use this operation to identify a Payment Service User in a decoupled approach.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation_identification(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentIdentificationRequest body:
        :return: PaymentIdentificationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_cancellation_identification_with_http_info(
                x_request_id, message_create_date_time, payment_id, **kwargs
            )
        return self.payment_cancellation_identification_with_http_info(
            x_request_id, message_create_date_time, payment_id, **kwargs
        )

    def payment_cancellation_identification_with_http_info(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment cancellation identification request.

        Use this operation to identify a Payment Service User in a decoupled approach.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_cancellation_identification_with_http_info(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentIdentificationRequest body:
        :return: PaymentIdentificationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["x_request_id", "message_create_date_time", "payment_id", "body"]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_cancellation_identification"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_cancellation_identification`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_cancellation_identification`"
            )
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_cancellation_identification`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/cancellation-identification",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentIdentificationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_confirmation(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment confirmation request by the PISP.

        This API is used to confirm a payment. Confirmation is required when the link 'ConfirmationRequired' is returned. Confirmation of a payment can be required in two cases 1) When its required by the ASPSP standard 2) when a payment fee is involved.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_confirmation(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param ConfirmationRequest body:
        :return: PaymentConfirmationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_confirmation_with_http_info(
                x_request_id, message_create_date_time, payment_id, **kwargs
            )
        return self.payment_confirmation_with_http_info(
            x_request_id, message_create_date_time, payment_id, **kwargs
        )

    def payment_confirmation_with_http_info(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment confirmation request by the PISP.

        This API is used to confirm a payment. Confirmation is required when the link 'ConfirmationRequired' is returned. Confirmation of a payment can be required in two cases 1) When its required by the ASPSP standard 2) when a payment fee is involved.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_confirmation_with_http_info(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param ConfirmationRequest body:
        :return: PaymentConfirmationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["x_request_id", "message_create_date_time", "payment_id", "body"]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_confirmation"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_confirmation`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_confirmation`"
            )
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_confirmation`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/confirmation",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentConfirmationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_identification(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment identification request.

        Use this operation to identify a PSU in decoupled approach. The response of the post payments api will provide a link to this api in the 'PostIdentificationForDecoupled' field if this step is required.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_identification(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentIdentificationRequest body:
        :return: PaymentIdentificationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_identification_with_http_info(
                x_request_id, message_create_date_time, payment_id, **kwargs
            )
        return self.payment_identification_with_http_info(
            x_request_id, message_create_date_time, payment_id, **kwargs
        )

    def payment_identification_with_http_info(
        self, x_request_id, message_create_date_time, payment_id, **kwargs
    ):
        """Payment identification request.

        Use this operation to identify a PSU in decoupled approach. The response of the post payments api will provide a link to this api in the 'PostIdentificationForDecoupled' field if this step is required.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_identification_with_http_info(x_request_id, message_create_date_time, payment_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param PaymentIdentificationRequest body:
        :return: PaymentIdentificationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ["x_request_id", "message_create_date_time", "payment_id", "body"]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_identification"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_identification`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_identification`"
            )
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_identification`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]

        query_params = []

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/identification",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentIdentificationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_initiate(
        self, x_request_id, message_create_date_time, psu_id, **kwargs
    ):
        r"""Payment initiation request.

        Use this operation to initiate a payment on behalf of the Payment Service User. Strong customer authentication might be required by the ASPSP, the response will indicate which step is required to complete the payment.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_initiate(x_request_id, message_create_date_time, psu_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str psu_id: This field can be filled with an ID from the Initiating Party which refers to the PSU.  (required)
        :param PaymentInitiationRequest body:
        :param str initiating_party_notification_url: The URL which will be used for notification service requests. The Open Banking Service supports two ways in which this field can be filled: * **Option A)** with an URL ending on /v2 or /v3, indicating the version of the Notification API implemented by the Initiating Party. In this case the URL called for notifications will be extended with /notification/status by the Open Banking Service. The 'NotificationVersion' field MUST NOT be filled. * **Option B)** with a full URL. The version information MUST BE provided in the 'NotificationVersion' field. In this case the provided URL will not be extended, and used as-is.
        :param str notification_version: The version which shall be used for notification service requests. The version is either v2 or v3.  If the NotificationVersion is given: -  The URLs for notification endpoints must be provided as full URLs. -  No endpoint specific extension will be added when calling out for notifications.  See the description of InitiatingPartyNotificationUrl for more information.
        :param str initiating_party_return_url: The callback URL for the redirection back to the Initiating Party after authorization.
        :param bool use_authorisation_landing_pages: If true, the Bank Selection Interface provided by Open Banking Service will be used to request required information from the PSU directly.
        :param str locale: 2-digit ISO-639 code for the language in which the Bank Selection Interface is displayed.  For special languages can be used 5-digit code like nl-BE, where first is ISO-639 langauge code and the second is ISO-3166 country code.  If not set, the language of the Bank Selection Interface is taken over from the end user’s browser configuration or the system configuration of the Bank Selection Interface server.
        :param bool app_redirect_preferred: Indicates whether the user uses mobile device\\tablet or PC
        :param datetime last_login: PSU Session information.  The time when the PSU last logged in with the TPP.
        :param str psu_ip_address: PSU Session information.  The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP . It shall be contained if and only if this request was actively initiated by the PSU.
        :param str psu_ip_port: PSU Session information.  The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
        :param str http_method: PSU Session information.  HTTP method used at the PSU-TPP interface. Available values - GET, POST, PUT, DELETE.
        :param str http_header_user_agent: PSU Session information.  The forwarded Agent header field of the HTTP request between PSU and TPP.
        :param str http_header_referer: PSU Session information.
        :param str http_header_accept: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str http_header_accept_charset: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str http_header_accept_encoding: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str http_header_accept_language: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str device_id: UUID (Universally Unique Identifier) for a device, which is used by the PSU. UUID identifies either a device or a device dependant application installation. In case of an installation identification this ID need to be unaltered until removal from device.
        :param str geo_location: The forwarded Geo Location of the corresponding http request between PSU and TPP.
        :param str signature: Conditionally required for iDEAL payments. The signature in the request should include a keyId with the value of fingerprint of the certificate
        :param str digest: Is contained if and only if the `Signature` element is contained in the header of the request.
        :param str confirm: If set to 'true' the transaction will be immediately confirmed by the Open Banking Service if confirmation of the payment by the Initiating Party is required by the ASPSP. <br>**Note:** This field is only applicable when the notification service is used by the Initiating Party to receive the status of the payment. When the notification is not used this flag can be set in the GET status API.
        :return: PaymentInitiationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_initiate_with_http_info(
                x_request_id, message_create_date_time, psu_id, **kwargs
            )
        return self.payment_initiate_with_http_info(
            x_request_id, message_create_date_time, psu_id, **kwargs
        )

    def payment_initiate_with_http_info(  # noqa: C901
        self, x_request_id, message_create_date_time, psu_id, **kwargs
    ):
        r"""Payment initiation request.

        Use this operation to initiate a payment on behalf of the Payment Service User. Strong customer authentication might be required by the ASPSP, the response will indicate which step is required to complete the payment.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_initiate_with_http_info(x_request_id, message_create_date_time, psu_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str psu_id: This field can be filled with an ID from the Initiating Party which refers to the PSU.  (required)
        :param PaymentInitiationRequest body:
        :param str initiating_party_notification_url: The URL which will be used for notification service requests. The Open Banking Service supports two ways in which this field can be filled: * **Option A)** with an URL ending on /v2 or /v3, indicating the version of the Notification API implemented by the Initiating Party. In this case the URL called for notifications will be extended with /notification/status by the Open Banking Service. The 'NotificationVersion' field MUST NOT be filled. * **Option B)** with a full URL. The version information MUST BE provided in the 'NotificationVersion' field. In this case the provided URL will not be extended, and used as-is.
        :param str notification_version: The version which shall be used for notification service requests. The version is either v2 or v3.  If the NotificationVersion is given: -  The URLs for notification endpoints must be provided as full URLs. -  No endpoint specific extension will be added when calling out for notifications.  See the description of InitiatingPartyNotificationUrl for more information.
        :param str initiating_party_return_url: The callback URL for the redirection back to the Initiating Party after authorization.
        :param bool use_authorisation_landing_pages: If true, the Bank Selection Interface provided by Open Banking Service will be used to request required information from the PSU directly.
        :param str locale: 2-digit ISO-639 code for the language in which the Bank Selection Interface is displayed.  For special languages can be used 5-digit code like nl-BE, where first is ISO-639 langauge code and the second is ISO-3166 country code.  If not set, the language of the Bank Selection Interface is taken over from the end user’s browser configuration or the system configuration of the Bank Selection Interface server.
        :param bool app_redirect_preferred: Indicates whether the user uses mobile device\\tablet or PC
        :param datetime last_login: PSU Session information.  The time when the PSU last logged in with the TPP.
        :param str psu_ip_address: PSU Session information.  The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP . It shall be contained if and only if this request was actively initiated by the PSU.
        :param str psu_ip_port: PSU Session information.  The forwarded IP Port header field consists of the corresponding HTTP request IP Port field between PSU and TPP, if available.
        :param str http_method: PSU Session information.  HTTP method used at the PSU-TPP interface. Available values - GET, POST, PUT, DELETE.
        :param str http_header_user_agent: PSU Session information.  The forwarded Agent header field of the HTTP request between PSU and TPP.
        :param str http_header_referer: PSU Session information.
        :param str http_header_accept: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str http_header_accept_charset: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str http_header_accept_encoding: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str http_header_accept_language: PSU Session information.  The forwarded IP Accept header fields consist of the corresponding HTTP request Accept header fields between PSU and TPP.
        :param str device_id: UUID (Universally Unique Identifier) for a device, which is used by the PSU. UUID identifies either a device or a device dependant application installation. In case of an installation identification this ID need to be unaltered until removal from device.
        :param str geo_location: The forwarded Geo Location of the corresponding http request between PSU and TPP.
        :param str signature: Conditionally required for iDEAL payments. The signature in the request should include a keyId with the value of fingerprint of the certificate
        :param str digest: Is contained if and only if the `Signature` element is contained in the header of the request.
        :param str confirm: If set to 'true' the transaction will be immediately confirmed by the Open Banking Service if confirmation of the payment by the Initiating Party is required by the ASPSP. <br>**Note:** This field is only applicable when the notification service is used by the Initiating Party to receive the status of the payment. When the notification is not used this flag can be set in the GET status API.
        :return: PaymentInitiationResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "x_request_id",
            "message_create_date_time",
            "psu_id",
            "body",
            "initiating_party_notification_url",
            "notification_version",
            "initiating_party_return_url",
            "use_authorisation_landing_pages",
            "locale",
            "app_redirect_preferred",
            "last_login",
            "psu_ip_address",
            "psu_ip_port",
            "http_method",
            "http_header_user_agent",
            "http_header_referer",
            "http_header_accept",
            "http_header_accept_charset",
            "http_header_accept_encoding",
            "http_header_accept_language",
            "device_id",
            "geo_location",
            "signature",
            "digest",
            "confirm",
        ]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}'"
                    " to method payment_initiate"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_initiate`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_initiate`"
            )
        # verify the required parameter 'psu_id' is set
        if "psu_id" not in params or params["psu_id"] is None:
            raise ValueError(
                "Missing the required parameter `psu_id` when calling `payment_initiate`"
            )

        collection_formats = {}

        path_params = {}
        if "psu_id" in params:
            path_params["psuId"] = params["psu_id"]

        query_params = []
        if "confirm" in params:
            query_params.append(("confirm", params["confirm"]))

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]
        if "initiating_party_notification_url" in params:
            header_params["InitiatingPartyNotificationUrl"] = params[
                "initiating_party_notification_url"
            ]
        if "notification_version" in params:
            header_params["NotificationVersion"] = params["notification_version"]
        if "initiating_party_return_url" in params:
            header_params["InitiatingPartyReturnUrl"] = params[
                "initiating_party_return_url"
            ]
        if "use_authorisation_landing_pages" in params:
            header_params["UseAuthorisationLandingPages"] = params[
                "use_authorisation_landing_pages"
            ]
        if "locale" in params:
            header_params["Locale"] = params["locale"]
        if "app_redirect_preferred" in params:
            header_params["AppRedirectPreferred"] = params["app_redirect_preferred"]
        if "last_login" in params:
            header_params["LastLogin"] = params["last_login"]
        if "psu_ip_address" in params:
            header_params["PsuIpAddress"] = params["psu_ip_address"]
        if "psu_ip_port" in params:
            header_params["PsuIpPort"] = params["psu_ip_port"]
        if "http_method" in params:
            header_params["HttpMethod"] = params["http_method"]
        if "http_header_user_agent" in params:
            header_params["HttpHeaderUserAgent"] = params["http_header_user_agent"]
        if "http_header_referer" in params:
            header_params["HttpHeaderReferer"] = params["http_header_referer"]
        if "http_header_accept" in params:
            header_params["HttpHeaderAccept"] = params["http_header_accept"]
        if "http_header_accept_charset" in params:
            header_params["HttpHeaderAcceptCharset"] = params[
                "http_header_accept_charset"
            ]
        if "http_header_accept_encoding" in params:
            header_params["HttpHeaderAcceptEncoding"] = params[
                "http_header_accept_encoding"
            ]
        if "http_header_accept_language" in params:
            header_params["HttpHeaderAcceptLanguage"] = params[
                "http_header_accept_language"
            ]
        if "device_id" in params:
            header_params["DeviceId"] = params["device_id"]
        if "geo_location" in params:
            header_params["GeoLocation"] = params["geo_location"]
        if "signature" in params:
            header_params["Signature"] = params["signature"]
        if "digest" in params:
            header_params["Digest"] = params["digest"]

        form_params = []
        local_var_files = {}

        body_params = None
        if "body" in params:
            body_params = params["body"]
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # HTTP header `Content-Type`
        header_params["Content-Type"] = self.api_client.select_header_content_type(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments",
            "POST",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentInitiationResponse",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )

    def payment_status(
        self, payment_id, x_request_id, message_create_date_time, **kwargs
    ):
        """Status of the payment request.

        Use this operation to retrieve the status of a payment.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_status(payment_id, x_request_id, message_create_date_time, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str confirm: If set to 'true' the transaction will be immediately confirmed by the Open Banking Service if confirmation of the payment by the Initiating Party is required by the ASPSP.
        :param str psu_ip_address: PSU Session information.  The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP . It shall be contained if and only if this request was actively initiated by the PSU.
        :param str signature: Conditionally required for iDEAL payments. The signature in the request should include a keyId with the value of fingerprint of the certificate
        :param str digest: Is contained if and only if the `Signature` element is contained in the header of the request.
        :return: PaymentDetailedInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs["_return_http_data_only"] = True
        if kwargs.get("async_req"):
            return self.payment_status_with_http_info(
                payment_id, x_request_id, message_create_date_time, **kwargs
            )
        return self.payment_status_with_http_info(
            payment_id, x_request_id, message_create_date_time, **kwargs
        )

    def payment_status_with_http_info(
        self, payment_id, x_request_id, message_create_date_time, **kwargs
    ):
        """Status of the payment request.

        Use this operation to retrieve the status of a payment.
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.payment_status_with_http_info(payment_id, x_request_id, message_create_date_time, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str payment_id: The Id used by the Open Banking Service to refer to a payment.  Optionally the payment can also be refered by the **InitiatingPartyReferenceId** or the **EndToEndId**, to do so start with **ref** or **e2e** prefixes followed by the respective identifier.  (required)
        :param str x_request_id: UUID for unique request identification.  (required)
        :param datetime message_create_date_time: The message create date time.  ISO 8601 DateTime.  (required)
        :param str confirm: If set to 'true' the transaction will be immediately confirmed by the Open Banking Service if confirmation of the payment by the Initiating Party is required by the ASPSP.
        :param str psu_ip_address: PSU Session information.  The forwarded IP Address header field consists of the corresponding HTTP request IP Address field between PSU and TPP . It shall be contained if and only if this request was actively initiated by the PSU.
        :param str signature: Conditionally required for iDEAL payments. The signature in the request should include a keyId with the value of fingerprint of the certificate
        :param str digest: Is contained if and only if the `Signature` element is contained in the header of the request.
        :return: PaymentDetailedInformation
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = [
            "payment_id",
            "x_request_id",
            "message_create_date_time",
            "confirm",
            "psu_ip_address",
            "signature",
            "digest",
        ]
        all_params.append("async_req")
        all_params.append("_return_http_data_only")
        all_params.append("_preload_content")
        all_params.append("_request_timeout")

        params = locals()
        for key, val in six.iteritems(params["kwargs"]):
            if key not in all_params:
                raise TypeError(
                    f"Got an unexpected keyword argument '{key}' to method payment_status"
                )
            params[key] = val
        del params["kwargs"]
        # verify the required parameter 'payment_id' is set
        if "payment_id" not in params or params["payment_id"] is None:
            raise ValueError(
                "Missing the required parameter `payment_id` when calling `payment_status`"
            )
        # verify the required parameter 'x_request_id' is set
        if "x_request_id" not in params or params["x_request_id"] is None:
            raise ValueError(
                "Missing the required parameter `x_request_id` when calling `payment_status`"
            )
        # verify the required parameter 'message_create_date_time' is set
        if (
            "message_create_date_time" not in params
            or params["message_create_date_time"] is None
        ):
            raise ValueError(
                "Missing the required parameter `message_create_date_time` when calling `payment_status`"
            )

        collection_formats = {}

        path_params = {}
        if "payment_id" in params:
            path_params["paymentId"] = params["payment_id"]

        query_params = []
        if "confirm" in params:
            query_params.append(("confirm", params["confirm"]))

        header_params = {}
        if "x_request_id" in params:
            header_params["X-Request-ID"] = params["x_request_id"]
        if "message_create_date_time" in params:
            header_params["MessageCreateDateTime"] = params["message_create_date_time"]
        if "psu_ip_address" in params:
            header_params["PsuIpAddress"] = params["psu_ip_address"]
        if "signature" in params:
            header_params["Signature"] = params["signature"]
        if "digest" in params:
            header_params["Digest"] = params["digest"]

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params["Accept"] = self.api_client.select_header_accept(
            ["application/json"]
        )

        # Authentication setting
        auth_settings = ["Authorization"]

        return self.api_client.call_api(
            "/ob/pis/v3/payments/{paymentId}/status",
            "GET",
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type="PaymentDetailedInformation",
            auth_settings=auth_settings,
            async_req=params.get("async_req"),
            _return_http_data_only=params.get("_return_http_data_only"),
            _preload_content=params.get("_preload_content", True),
            _request_timeout=params.get("_request_timeout"),
            collection_formats=collection_formats,
        )
