
"""Open Banking Reach + AIS  PIS

# REACH The Reach Directory is used to get the a list of ASPSP's which can be reached for a  specific Service. **Sandbox** The following authorization token can be used to test in the sandbox (unlike a real token this one doesn't expire) 97fb13a74c712d8c7a50476e71769eaf  # AIS There are several possible flows (sequence of API calls) to obtain a consent before Account Information data can be retrieved. Which API's are required depend on the ASPSP (the bank of the PSU) and the chosen strong customer authentication approach. The response of an API call will indicate in the Links section which next API call is required to complete the consent request.  **Sandbox** Several AspspId's are available to test specific account information scenario's, see sandbox     documentation. The following authorization token can be used to test in the sandbox (unlike a real token this one     doesn't expire) **d5bd895a4080dbbb469a207460b6fca**  # PIS There are several flows (sequence of API calls) to complete a payment. Which API's are required depend on the choosen `PaymentProduct`, ASPSP (debtor bank) and the chosen strong customer authentication approach. The response of an API call will indicate in the 'Links' section which next API call is required to complete the payment. Both PSD2 and IDEAL payments are supported. **Sandbox** Several AspspId's are available to test specific PSD2 payment initiation scenario's, see sandbox documentation.  The following authorization token can be used to test in the sandbox (unlike a real token this one doesn't expire): **97fb13a74c712d8c7a50476e71769eaf**   # noqa: E501

OpenAPI spec version: 3.2.0 + 3.6.0 + 3.7.0
    
Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PaymentDetailedInformation:
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payment_product_used': 'PaymentProductEnum',
        'common_payment_data': 'CommonPaymentDataResponse',
        'links': 'StatusResponseLinks',
        'use_waiting_screen': 'bool'
    }

    attribute_map = {
        'payment_product_used': 'PaymentProductUsed',
        'common_payment_data': 'CommonPaymentData',
        'links': 'Links',
        'use_waiting_screen': 'UseWaitingScreen'
    }

    def __init__(self, payment_product_used=None, common_payment_data=None, links=None, use_waiting_screen=None):  # noqa: E501
        """PaymentDetailedInformation - a model defined in Swagger"""  # noqa: E501
        self._payment_product_used = None
        self._common_payment_data = None
        self._links = None
        self._use_waiting_screen = None
        self.discriminator = None
        if payment_product_used is not None:
            self.payment_product_used = payment_product_used
        if common_payment_data is not None:
            self.common_payment_data = common_payment_data
        if links is not None:
            self.links = links
        if use_waiting_screen is not None:
            self.use_waiting_screen = use_waiting_screen

    @property
    def payment_product_used(self):
        """Gets the payment_product_used of this PaymentDetailedInformation.  # noqa: E501

        :return: The payment_product_used of this PaymentDetailedInformation.  # noqa: E501
        :rtype: PaymentProductEnum
        """
        return self._payment_product_used

    @payment_product_used.setter
    def payment_product_used(self, payment_product_used):
        """Sets the payment_product_used of this PaymentDetailedInformation.

        :param payment_product_used: The payment_product_used of this PaymentDetailedInformation.  # noqa: E501
        :type: PaymentProductEnum
        """

        self._payment_product_used = payment_product_used

    @property
    def common_payment_data(self):
        """Gets the common_payment_data of this PaymentDetailedInformation.  # noqa: E501

        :return: The common_payment_data of this PaymentDetailedInformation.  # noqa: E501
        :rtype: CommonPaymentDataResponse
        """
        return self._common_payment_data

    @common_payment_data.setter
    def common_payment_data(self, common_payment_data):
        """Sets the common_payment_data of this PaymentDetailedInformation.

        :param common_payment_data: The common_payment_data of this PaymentDetailedInformation.  # noqa: E501
        :type: CommonPaymentDataResponse
        """

        self._common_payment_data = common_payment_data

    @property
    def links(self):
        """Gets the links of this PaymentDetailedInformation.  # noqa: E501

        :return: The links of this PaymentDetailedInformation.  # noqa: E501
        :rtype: StatusResponseLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PaymentDetailedInformation.

        :param links: The links of this PaymentDetailedInformation.  # noqa: E501
        :type: StatusResponseLinks
        """

        self._links = links

    @property
    def use_waiting_screen(self):
        """Gets the use_waiting_screen of this PaymentDetailedInformation.  # noqa: E501

        if `true` the Initiating Party should show a waiting screen even if the the RedirectUrl is provided. On the waiting screen a redirection button should be placed. Click on the button should redirect the PSU to the link provided in the `RedirectUrl` field.   # noqa: E501

        :return: The use_waiting_screen of this PaymentDetailedInformation.  # noqa: E501
        :rtype: bool
        """
        return self._use_waiting_screen

    @use_waiting_screen.setter
    def use_waiting_screen(self, use_waiting_screen):
        """Sets the use_waiting_screen of this PaymentDetailedInformation.

        if `true` the Initiating Party should show a waiting screen even if the the RedirectUrl is provided. On the waiting screen a redirection button should be placed. Click on the button should redirect the PSU to the link provided in the `RedirectUrl` field.   # noqa: E501

        :param use_waiting_screen: The use_waiting_screen of this PaymentDetailedInformation.  # noqa: E501
        :type: bool
        """

        self._use_waiting_screen = use_waiting_screen

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PaymentDetailedInformation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PaymentDetailedInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
