# coding: utf-8

"""
    Open Banking Payment Initiation Service

    ### Introduction There are several flows (sequence of API calls) to complete a payment. Which API's are required depend on the choosen `PaymentProduct`, ASPSP (debtor bank) and the chosen strong customer authentication approach. The response of an API call will indicate in the 'Links' section which next API call is required to complete the payment. Both PSD2 and IDEAL payments are supported.  #### PSD2 Sandbox Several AspspId's are available to test specific PSD2 payment initiation scenario's, see sandbox documentation.  The following authorization token can be used to test in the sandbox (unlike a real token this one doesn't expire): **97fb13a74c712d8c7a50476e71769eaf**   # noqa: E501

    OpenAPI spec version: 3.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AmountBreakdown(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_amount': 'str',
        'shipping_cost': 'str'
    }

    attribute_map = {
        'order_amount': 'OrderAmount',
        'shipping_cost': 'ShippingCost'
    }

    def __init__(self, order_amount=None, shipping_cost=None):  # noqa: E501
        """AmountBreakdown - a model defined in Swagger"""  # noqa: E501
        self._order_amount = None
        self._shipping_cost = None
        self.discriminator = None
        self.order_amount = order_amount
        self.shipping_cost = shipping_cost

    @property
    def order_amount(self):
        """Gets the order_amount of this AmountBreakdown.  # noqa: E501

        Order amount. Possible to use for iDEAL payments, only in the fast-checkout flow.   # noqa: E501

        :return: The order_amount of this AmountBreakdown.  # noqa: E501
        :rtype: str
        """
        return self._order_amount

    @order_amount.setter
    def order_amount(self, order_amount):
        """Sets the order_amount of this AmountBreakdown.

        Order amount. Possible to use for iDEAL payments, only in the fast-checkout flow.   # noqa: E501

        :param order_amount: The order_amount of this AmountBreakdown.  # noqa: E501
        :type: str
        """
        if order_amount is None:
            raise ValueError("Invalid value for `order_amount`, must not be `None`")  # noqa: E501

        self._order_amount = order_amount

    @property
    def shipping_cost(self):
        """Gets the shipping_cost of this AmountBreakdown.  # noqa: E501

        Shipping cost. Possible to use for iDEAL payments, only in the fast-checkout flow.   # noqa: E501

        :return: The shipping_cost of this AmountBreakdown.  # noqa: E501
        :rtype: str
        """
        return self._shipping_cost

    @shipping_cost.setter
    def shipping_cost(self, shipping_cost):
        """Sets the shipping_cost of this AmountBreakdown.

        Shipping cost. Possible to use for iDEAL payments, only in the fast-checkout flow.   # noqa: E501

        :param shipping_cost: The shipping_cost of this AmountBreakdown.  # noqa: E501
        :type: str
        """
        if shipping_cost is None:
            raise ValueError("Invalid value for `shipping_cost`, must not be `None`")  # noqa: E501

        self._shipping_cost = shipping_cost

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AmountBreakdown, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AmountBreakdown):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
