# coding: utf-8

"""
    Open Banking Payment Initiation Service

    ### Introduction There are several flows (sequence of API calls) to complete a payment. Which API's are required depend on the choosen `PaymentProduct`, ASPSP (debtor bank) and the chosen strong customer authentication approach. The response of an API call will indicate in the 'Links' section which next API call is required to complete the payment. Both PSD2 and IDEAL payments are supported.  #### PSD2 Sandbox Several AspspId's are available to test specific PSD2 payment initiation scenario's, see sandbox documentation.  The following authorization token can be used to test in the sandbox (unlike a real token this one doesn't expire): **97fb13a74c712d8c7a50476e71769eaf**   # noqa: E501

    OpenAPI spec version: 3.9.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ScaMethods(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authentication_type': 'str',
        'authentication_method_id': 'str',
        'version': 'str',
        'name': 'str',
        'explanation': 'str'
    }

    attribute_map = {
        'authentication_type': 'AuthenticationType',
        'authentication_method_id': 'AuthenticationMethodId',
        'version': 'Version',
        'name': 'Name',
        'explanation': 'Explanation'
    }

    def __init__(self, authentication_type=None, authentication_method_id=None, version=None, name=None, explanation=None):  # noqa: E501
        """ScaMethods - a model defined in Swagger"""  # noqa: E501
        self._authentication_type = None
        self._authentication_method_id = None
        self._version = None
        self._name = None
        self._explanation = None
        self.discriminator = None
        self.authentication_type = authentication_type
        self.authentication_method_id = authentication_method_id
        if version is not None:
            self.version = version
        if name is not None:
            self.name = name
        if explanation is not None:
            self.explanation = explanation

    @property
    def authentication_type(self):
        """Gets the authentication_type of this ScaMethods.  # noqa: E501

        Type of the SCA authentication method. The following methods are commonly seen coming from the ASPSP: -  SMS_OTP: The PSU will receive a One Time Password via SMS -  CHIP_OTP: The PSU will be presented with a picture or text to create a One Time Password using their bank card -  PHOTO_OTP: The PSU will be presented with a picture to create a One Time Password -  PUSH_OTP: The PSU will receive a One Time Password via push notification on their mobile device -  SMTP_OTP: The PSU will receive a One Time Password via email   # noqa: E501

        :return: The authentication_type of this ScaMethods.  # noqa: E501
        :rtype: str
        """
        return self._authentication_type

    @authentication_type.setter
    def authentication_type(self, authentication_type):
        """Sets the authentication_type of this ScaMethods.

        Type of the SCA authentication method. The following methods are commonly seen coming from the ASPSP: -  SMS_OTP: The PSU will receive a One Time Password via SMS -  CHIP_OTP: The PSU will be presented with a picture or text to create a One Time Password using their bank card -  PHOTO_OTP: The PSU will be presented with a picture to create a One Time Password -  PUSH_OTP: The PSU will receive a One Time Password via push notification on their mobile device -  SMTP_OTP: The PSU will receive a One Time Password via email   # noqa: E501

        :param authentication_type: The authentication_type of this ScaMethods.  # noqa: E501
        :type: str
        """
        if authentication_type is None:
            raise ValueError("Invalid value for `authentication_type`, must not be `None`")  # noqa: E501

        self._authentication_type = authentication_type

    @property
    def authentication_method_id(self):
        """Gets the authentication_method_id of this ScaMethods.  # noqa: E501

        Id of the authentication method. Used in subsequent API calls to refer to the authentication method.   # noqa: E501

        :return: The authentication_method_id of this ScaMethods.  # noqa: E501
        :rtype: str
        """
        return self._authentication_method_id

    @authentication_method_id.setter
    def authentication_method_id(self, authentication_method_id):
        """Sets the authentication_method_id of this ScaMethods.

        Id of the authentication method. Used in subsequent API calls to refer to the authentication method.   # noqa: E501

        :param authentication_method_id: The authentication_method_id of this ScaMethods.  # noqa: E501
        :type: str
        """
        if authentication_method_id is None:
            raise ValueError("Invalid value for `authentication_method_id`, must not be `None`")  # noqa: E501

        self._authentication_method_id = authentication_method_id

    @property
    def version(self):
        """Gets the version of this ScaMethods.  # noqa: E501

        Version of the method.   # noqa: E501

        :return: The version of this ScaMethods.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ScaMethods.

        Version of the method.   # noqa: E501

        :param version: The version of this ScaMethods.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def name(self):
        """Gets the name of this ScaMethods.  # noqa: E501

        Name of the method in readable form. This name shall be used by the TPP when presenting a list of authentication methods to the PSU, if available.   # noqa: E501

        :return: The name of this ScaMethods.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ScaMethods.

        Name of the method in readable form. This name shall be used by the TPP when presenting a list of authentication methods to the PSU, if available.   # noqa: E501

        :param name: The name of this ScaMethods.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def explanation(self):
        """Gets the explanation of this ScaMethods.  # noqa: E501

        Detailed information about the SCA method, meant for the PSU.   # noqa: E501

        :return: The explanation of this ScaMethods.  # noqa: E501
        :rtype: str
        """
        return self._explanation

    @explanation.setter
    def explanation(self, explanation):
        """Sets the explanation of this ScaMethods.

        Detailed information about the SCA method, meant for the PSU.   # noqa: E501

        :param explanation: The explanation of this ScaMethods.  # noqa: E501
        :type: str
        """

        self._explanation = explanation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScaMethods, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScaMethods):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
