# coding: utf-8

"""
    Open Banking Account Information V3

    There are several possible flows (sequence of API calls) to obtain a consent before Account Information data can be retrieved. Which API's are required depend on the ASPSP (the bank of the PSU) and the chosen strong customer authentication approach. The response of an API call will indicate in the 'Links' section which next API call is required to complete the consent request.  #### PSD2 Sandbox  Several AspspId's are available to test specific account information scenario's, see sandbox documentation.  The following authorization token can be used to test in the sandbox (unlike a real token this one doesn't expire): **d5bd895a4080dbbb469a207460b6fca**   # noqa: E501

    OpenAPI spec version: 3.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PutRegistrationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'psu_id': 'str',
        'registration_status': 'RegistrationStatusEnum',
        'accounts': 'list[PutRegistrationRequestAccounts]'
    }

    attribute_map = {
        'psu_id': 'PsuId',
        'registration_status': 'RegistrationStatus',
        'accounts': 'Accounts'
    }

    def __init__(self, psu_id=None, registration_status=None, accounts=None):  # noqa: E501
        """PutRegistrationRequest - a model defined in Swagger"""  # noqa: E501
        self._psu_id = None
        self._registration_status = None
        self._accounts = None
        self.discriminator = None
        if psu_id is not None:
            self.psu_id = psu_id
        if registration_status is not None:
            self.registration_status = registration_status
        if accounts is not None:
            self.accounts = accounts

    @property
    def psu_id(self):
        """Gets the psu_id of this PutRegistrationRequest.  # noqa: E501

        This field can be filled with an ID from the Initiating Party which refers to the PSU.   # noqa: E501

        :return: The psu_id of this PutRegistrationRequest.  # noqa: E501
        :rtype: str
        """
        return self._psu_id

    @psu_id.setter
    def psu_id(self, psu_id):
        """Sets the psu_id of this PutRegistrationRequest.

        This field can be filled with an ID from the Initiating Party which refers to the PSU.   # noqa: E501

        :param psu_id: The psu_id of this PutRegistrationRequest.  # noqa: E501
        :type: str
        """

        self._psu_id = psu_id

    @property
    def registration_status(self):
        """Gets the registration_status of this PutRegistrationRequest.  # noqa: E501


        :return: The registration_status of this PutRegistrationRequest.  # noqa: E501
        :rtype: RegistrationStatusEnum
        """
        return self._registration_status

    @registration_status.setter
    def registration_status(self, registration_status):
        """Sets the registration_status of this PutRegistrationRequest.


        :param registration_status: The registration_status of this PutRegistrationRequest.  # noqa: E501
        :type: RegistrationStatusEnum
        """

        self._registration_status = registration_status

    @property
    def accounts(self):
        """Gets the accounts of this PutRegistrationRequest.  # noqa: E501


        :return: The accounts of this PutRegistrationRequest.  # noqa: E501
        :rtype: list[PutRegistrationRequestAccounts]
        """
        return self._accounts

    @accounts.setter
    def accounts(self, accounts):
        """Sets the accounts of this PutRegistrationRequest.


        :param accounts: The accounts of this PutRegistrationRequest.  # noqa: E501
        :type: list[PutRegistrationRequestAccounts]
        """

        self._accounts = accounts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PutRegistrationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PutRegistrationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
